### ISSUE TITLE
Question: Gulp support?

### ISSUE THREAD

**Issue by marcellodesales** [rumpl/depcheck#17]
Hi there,

I'm looking for a Gulp support for addressing this problem... Have you integrated your app to Gulp or Grunt? Any suggestions? I can submit a PR if there's interest...

thanks!

**Comment by goloroden** [comment]
+1 for Grunt support, would <3 this :-)

**Comment by rumpl** [comment]
Ok guys, [grunt plugin](https://github.com/rumpl/grunt-depcheck) is coming soon, a gulp one after that.

**Comment by marcellodesales** [comment]
@rumpl Awesome... I would love to contribute with the gulp one!

thanks!

**Comment by vmeurisse** [comment]
For those interested, here is my way of doing the gulp support ;)

```js
gulp.task('_checkdeps', function() {
	return new Promise(function(fulfill, reject) {
		var depcheck = require('depcheck');
		var options = {
			'ignoreDirs': ['build', 'client']
		};
		depcheck(__dirname, options, function(unused) {
			if (Object.keys(unused.invalidFiles).length) {
				console.log('Unable to parse some files');
				console.log(unused.invalidFiles);
				reject(new Error('Unable to parse some files'));
				return;
			}
			if (unused.dependencies.length || unused.devDependencies.length) {
				console.log('You have some unused dependencies');
				console.log(unused.dependencies.concat(unused.devDependencies));
				reject(new Error('You have some unused dependencies'));
				return;
			}
			fulfill();
		});
	});
});
```

**Comment by mcasimir** [comment]
https://github.com/mcasimir/gulp-depcheck

**Comment by rumpl** [comment]
@mcasimir That's awesome!
I just created an organization for depcheck, would you want your repo to be in there ?
I can add you to the organization.

Thanks for the module! :)

**Comment by goloroden** [comment]
Great news 🎉 

The [gulp-depcheck](https://github.com/depcheck/gulp-depcheck) module is now part of this organisation 😊
